// prisma/seed.ts
import { PrismaClient } from "@prisma/client";
const prisma = new PrismaClient();

async function main() {
    const items = [
        {
            menuId: "A01",
            menuName: "สเปเชียลมากิโรล",
            price: 220,
            discount: 10,
            netPrice: 210,
            category: "ซูชิ",
            imageUrl: "https://images.unsplash.com/photo-1712725214706-e564b8dd1bbe?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxzdXNoaSUyMHJvbGwlMjBtYWtpfGVufDF8fHx8MTc2Mzk5NjgwNXww&ixlib=rb-4.1.0&q=80&w=1080",
        },
        {
            menuId: "A02",
            menuName: "ซูชิโรล",
            price: 40,
            discount: 0,
            netPrice: 40,
            category: "ซูชิ",
            imageUrl: "https://media.istockphoto.com/id/1224916255/th/%E0%B8%A3%E0%B8%B9%E0%B8%9B%E0%B8%96%E0%B9%88%E0%B8%B2%E0%B8%A2/%E0%B8%8B%E0%B8%B9%E0%B8%8A%E0%B8%B4%E0%B8%A1%E0%B8%B2%E0%B8%81%E0%B8%B4%E0%B8%81%E0%B8%B1%E0%B8%9A%E0%B8%9B%E0%B8%A5%E0%B8%B2%E0%B9%81%E0%B8%8B%E0%B8%A5%E0%B8%A1%E0%B8%AD%E0%B8%99%E0%B8%81%E0%B8%B8%E0%B9%89%E0%B8%87%E0%B9%81%E0%B8%95%E0%B8%87%E0%B8%81%E0%B8%A7%E0%B8%B2.jpg?s=612x612&w=0&k=20&c=WrspGGUz2XpkWYfF11f_HDN6Vwx_wu-HF07d15WUHRk=",
        },
        {
            menuId: "A03",
            menuName: "ปลาหมึกกล้วยทั้งตัว",
            price: 40,
            discount: 0,
            netPrice: 40,
            category: "ซูชิ",
            imageUrl: "https://sushiro.co.th/wp-content/uploads/2021/03/071.jpg",
        },
        {
            menuId: "A04",
            menuName: "คานิคามะกับหัวหอม",
            price: 40,
            discount: 0,
            netPrice: 40,
            category: "ซูชิ",
            imageUrl: "https://sushiro.co.th/wp-content/uploads/2021/03/067.jpg",
        },
        {
            menuId: "A05",
            menuName: "ปลาหมึกกับไข่ปลาทาราโกะ",
            price: 60,
            discount: 0,
            netPrice: 60,
            category: "ซูชิ",
            imageUrl: "https://sushiro.co.th/wp-content/uploads/2021/03/072.jpg",
        },
        {
            menuId: "A06",
            menuName: "กุ้งแดงใหญ่ย่างกับเลมอนโรยเกลือ",
            price: 40,
            discount: 0,
            netPrice: 40,
            category: "ซูชิ",
            imageUrl: "https://sushiro.co.th/wp-content/uploads/2021/03/057-2.jpg",
        },
        {
            menuId: "A07",
            menuName: "กุ้งย่างชีท",
            price: 40,
            discount: 0,
            netPrice: 40,
            category: "ซูชิ",
            imageUrl: "https://sushiro.co.th/wp-content/uploads/2021/03/053.jpg",
        },
        {
            menuId: "A08",
            menuName: "มารูโกะ",
            price: 40,
            discount: 0,
            netPrice: 40,
            category: "ซูชิ",
            imageUrl: "https://sushiro.co.th/wp-content/uploads/2021/03/001.jpg",
        },
        {
            menuId: "B01",
            menuName: "ซูชิแซลมอน",
            price: 180,
            discount: 21,
            netPrice: 159,
            category: "ชุดเซทซูชิ",
            imageUrl: "https://images.unsplash.com/photo-1680675228874-9b9963812b7c?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxzYWxtb24lMjBzdXNoaSUyMG5pZ2lyaXxlbnwxfHx8fDE3NjM5NzAzMjZ8MA&ixlib=rb-4.1.0&q=80&w=1080",
        },
        {
            menuId: "B02",
            menuName: "เซทซูชิพิเศษ",
            price: 480,
            discount: 81,
            netPrice: 399,
            category: "ชุดเซทซูชิ",
            imageUrl: "https://images.unsplash.com/photo-1696091811927-6b9552931f70?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxzdXNoaSUyMGNvbWJvJTIwc2V0fGVufDF8fHx8MTc2NDAxMzQ2M3ww&ixlib=rb-4.1.0&q=80&w=1080",
        },
        {
            menuId: "B03",
            menuName: "ซูชิมินิเซต A",
            price: 100,
            discount: 0,
            netPrice: 100,
            category: "ชุดเซทซูชิ",
            imageUrl: "https://www.wakanafooddelivery.com/images/product/mini-sushi-set-a.jpg?v=1",
        },
        {
            menuId: "B04",
            menuName: "ซูชิมินิเซต B",
            price: 100,
            discount: 0,
            netPrice: 100,
            category: "ชุดเซทซูชิ",
            imageUrl: "https://www.wakanafooddelivery.com/images/product/sushi_minisetB500x500.jpg?v=1",
        },
        {
            menuId: "B05",
            menuName: "ซูชิมินิเซต C",
            price: 100,
            discount: 0,
            netPrice: 100,
            category: "ชุดเซทซูชิ",
            imageUrl: "https://www.wakanafooddelivery.com/images/product/mini-sushi-set-c.jpg?v=1",
        },
        {
            menuId: "B06",
            menuName: "ซูชิมินิเซต D",
            price: 250,
            discount: 0,
            netPrice: 250,
            category: "ชุดเซทซูชิ",
            imageUrl: "https://media.istockphoto.com/id/1053855452/th/%E0%B8%A3%E0%B8%B9%E0%B8%9B%E0%B8%96%E0%B9%88%E0%B8%B2%E0%B8%A2/%E0%B8%8A%E0%B8%B8%E0%B8%94%E0%B8%8B%E0%B8%B9%E0%B8%8A%E0%B8%B4%E0%B8%9A%E0%B8%99%E0%B8%88%E0%B8%B2%E0%B8%99%E0%B9%84%E0%B8%A1%E0%B9%89%E0%B9%84%E0%B8%9C%E0%B9%88.jpg?s=612x612&w=0&k=20&c=26MP9xeXpK2dn3Nad0d9Uj0Yr5CXjIqFn9p2rFuOq7k=",
        },
        {
            menuId: "C01",
            menuName: "คอมโบปาร์ตี้",
            price: 450,
            discount: 0,
            netPrice: 450,
            category: "ชุดปาร์ตี้",
            imageUrl: "https://images.unsplash.com/photo-1638866381709-071747b518c8?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHx0dW5hJTIwc2FzaGltaXxlbnwxfHx8fDE3NjQwNTYzMzl8MA&ixlib=rb-4.1.0&q=80&w=1080",
        },
        {
            menuId: "C02",
            menuName: "แคลิฟอร์เนียโรล",
            price: 150,
            discount: 21,
            netPrice: 129,
            category: "ชุดปาร์ตี้",
            imageUrl: "https://images.unsplash.com/photo-1559410545-0bdcd187e0a6?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxjYWxpZm9ybmlhJTIwcm9sbCUyMHN1c2hpfGVufDF8fHx8MTc2Mzk3MDMyNXww&ixlib=rb-4.1.0&q=80&w=1080",
        },
        {
            menuId: "C03",
            menuName: "เซทซูชิพรีเมี่ยม",
            price: 650,
            discount: 0,
            netPrice: 650,
            category: "ชุดปาร์ตี้",
            imageUrl: "https://images.unsplash.com/photo-1625937751876-4515cd8e78bd?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxzdXNoaSUyMHBsYXR0ZXJ8ZW58MXx8fHwxNzYzOTk1MDcwfDA&ixlib=rb-4.1.0&q=80&w=1080",
        },
        {
            menuId: "C04",
            menuName: "คอมโบ ปาร์ตี้เซต",
            price: 1300,
            discount: 75,
            netPrice: 1225,
            category: "ชุดปาร์ตี้",
            imageUrl: "https://www.wakanafooddelivery.com/images/product/combo-party-sushi-sashimi.jpg?v=1",
        },
        {
            menuId: "C05",
            menuName: "แซลมอน เลิฟเวอร์",
            price: 1400,
            discount: 250,
            netPrice: 1150,
            category: "ชุดปาร์ตี้",
            imageUrl: "https://www.wakanafooddelivery.com/images/product/salmon-lover.jpg?v=1",
        },
        {
            menuId: "C06",
            menuName: "มินิ มัสสึ ปาร์ตี้เซต",
            price: 900,
            discount: 0,
            netPrice: 900,
            category: "ชุดปาร์ตี้",
            imageUrl: "https://www.wakanafooddelivery.com/images/product/matsu-mini-party.jpg?v=1",
        },
        {
            menuId: "C07",
            menuName: "แซลมอนฟลาวเวอร์",
            price: 1350,
            discount: 21,
            netPrice: 1329,
            category: "ชุดปาร์ตี้",
            imageUrl: "https://www.wakanafooddelivery.com/images/product/salmon-flower.jpg?v=1",
        },
        {
            menuId: "D01",
            menuName: "แซลมอน ซาชิมิ ไซส์ XS (160กรัม)",
            price: 300,
            discount: 0,
            netPrice: 300,
            category: "ซาชิมิ",
            imageUrl: "https://www.wakanafooddelivery.com/images/product/salmon-sashimi-xs.png?v=1",
        },
        {
            menuId: "D02",
            menuName: "พรีเมียมซาชิมิ เซต A",
            price: 590,
            discount: 21,
            netPrice: 569,
            category: "ซาชิมิ",
            imageUrl: "https://www.wakanafooddelivery.com/images/product/premium-sashimi-set-a.jpg?v=1",
        },
        {
            menuId: "E01",
            menuName: "ชาไทย",
            price: 49,
            discount: 0,
            netPrice: 49,
            category: "เครื่องดื่ม",
            imageUrl: "https://www.wakanafooddelivery.com/images/product/thai-black-tea.jpg?v=1",
        },
        {
            menuId: "E02",
            menuName: "ชาไทยลาเต้",
            price: 49,
            discount: 0,
            netPrice: 49,
            category: "เครื่องดื่ม",
            imageUrl: "https://www.wakanafooddelivery.com/images/product/%E0%B8%8A%E0%B8%B2%E0%B9%84%E0%B8%97%E0%B8%A2%E0%B8%A5%E0%B8%B2%E0%B9%80%E0%B8%95%E0%B9%89500x500.jpg?v=1",
        },
    ];

    for (const item of items) {
        await prisma.menuItem.upsert({
            where: { menuId: item.menuId },
            update: {
                name: item.menuName,
                price: item.price,
                detail: item.detail || "",
                discount: item.discount,
                netPrice: item.netPrice,
                category: item.category,
                imageUrl: item.imageUrl,
            },
            create: item,
        });
    }

    console.log(`Seeded ${items.length} menu items`);
}

main()
    .catch((e) => {
        console.error(e);
        process.exit(1);
    })
    .finally(async () => {
        await prisma.$disconnect();
    });